### ISSUE TITLE
some error..

### ISSUE THREAD

**Issue by Unixware** [david63/logconnections#2]
Hi 

Some users can't login on my forum on 1st attempt they see this error on the screen:

[phpBB debug] PHP Warning: in file [ROOT]/ext/david63/logconnections/controller/main_controller.php on line 125: in_array() 
expects parameter 2 to be array, null given

my config: 
extension Version 2.1.0-rc4
phpBB 3.2.8
PHP version:	7.2.26
Database server:	MySQL(i) 10.3.18-MariaDB

thanks

**Comment by miri4ever** [comment]
Got the same problem sometimes at PHPBB 3.3.0. Before this it never  happen, but since PHPB 3.3.0 my Server is also running PHP 7.3 and before it was 7.0, this could be also a problem. This error not happens all the times and after a few try login might work.

**Comment by david63** [comment]
Have you updated to the latest version as that error message is impossible in the latest version?

**Comment by Unixware** [comment]
for me the extension works -its just I forgot to update my report! sorry about it!
