### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by ashishpatel1992** [david63/logconnections#3]
Users are unable to login not even administrators
error
```
[phpBB Debug] PHP Warning: in file [ROOT]/ext/david63/logconnections/controller/main_controller.php on line 124: in_array() expects parameter 2 to be array, null given
Revenir à la page d’index
Erreur générale
SQL ERROR [ mysqli ]

Column 'log_operation' cannot be null [1048]

Une erreur SQL est survenue lors du chargement de la page. Si ce problème persiste, veuillez contacter l’administrateur du forum.
```

**Comment by david63** [comment]
No idea what you are using but there is no "log_operation" in this extension

**Comment by Kreeman** [comment]
Same issue here ... The SQL error comes up at screen instead of the board's default error(login redirect) message/information "The submitted form was invalid" .... Commonly shows up at ajax login following the immediate logout of an account ...

**Comment by david63** [comment]
Cannot reproduce
